#!/usr/bin/env python3
"""Generate KETI launcher icons and launch screens for every Flutter app in this repo.

The source of truth is `tools/assets/keti_logo.png`, the two-line KETI wordmark. Two
things are cut out of it:

  * the `KETI` symbol block (top-left), which is the only part that survives being
    squeezed into a square launcher icon
  * the full wordmark, which is what belongs on a launch screen where there is room to
    read it

Run from the repository root:

    python3 tools/build_keti_branding.py

It writes into each app's `android/app/src/main/res` and is idempotent, so it can be
re-run whenever the logo changes.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - dependency hint is the useful behaviour
    sys.exit("Pillow is required: pip3 install --break-system-packages Pillow")

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "tools" / "assets" / "keti_logo.png"

# Android res directories that carry the app icon, and their baseline multipliers.
DENSITIES = {
    "mdpi": 1.0,
    "hdpi": 1.5,
    "xhdpi": 2.0,
    "xxhdpi": 3.0,
    "xxxhdpi": 4.0,
}

# Legacy icons are 48dp; adaptive icon layers are 108dp with only the middle 72dp
# guaranteed visible, so the mark is sized against that safe zone rather than the layer.
LEGACY_DP = 48
ADAPTIVE_DP = 108
ADAPTIVE_SAFE_FRACTION = 72 / 108

# Launch screen art is sized in dp of width; 220dp reads clearly on a tablet without
# dominating the screen.
SPLASH_DP = 220

# System splash geometry from the Android 12 spec: a 288dp canvas, of which only the inner
# 160dp survives the circular mask.
SPLASH_ICON_DP = 288
SPLASH_ICON_CONTENT_DP = 160

# The white of the light console design, so the launch screen does not flash a different
# white than the app itself.
BACKGROUND = (255, 255, 255, 255)

APPS = [
    ("Drive Pilot", ROOT / "android"),
    ("PLEOS Multimode", ROOT / "apps" / "pleos_multimode" / "android"),
    ("PLEOS Reconfig", ROOT / "apps" / "pleos_reconfig_console" / "android"),
    ("PLEOS Reconfig Studio", ROOT / "apps" / "pleos_reconfig_studio" / "android"),
    ("PLEOS Reconfig HMI", ROOT / "apps" / "pleos_reconfig_hmi" / "android"),
]

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">#FFFFFFFF</color>
</resources>
"""

LAUNCH_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build_keti_branding.py -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/ic_launcher_background" />
    <item>
        <bitmap
            android:gravity="center"
            android:src="@drawable/splash_keti" />
    </item>
</layer-list>
"""

# Android 12 replaced the legacy windowBackground splash with the system SplashScreen,
# which ignores `launch_background` entirely and shows a masked icon instead. Without this
# the launch screen is a blank white window on every current device -- which is exactly
# what the tablet showed.
LAUNCH_V31_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build_keti_branding.py -->
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <!-- Kept for the window behind the system splash. -->
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:windowSplashScreenBackground">@color/ic_launcher_background</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_icon</item>
    </style>
</resources>
"""


# Where the `KETI` symbol block sits inside the wordmark, as fractions of the logo. These
# are measured from the vendored logo rather than detected: the gap between the block and
# the Korean name beside it is a single pixel wide, so no gap-width rule can separate them
# without also splitting `KETI` at its own letter spacing.
MARK_RIGHT = 0.35
MARK_BOTTOM = 0.72
# The block is close to 2:1. Checked so a re-exported logo with a different layout fails
# loudly instead of quietly shipping a wrong icon.
MARK_ASPECT = (1.6, 2.4)


def load_parts(logo: Path) -> tuple[Image.Image, Image.Image]:
    """Returns (square-ish `KETI` mark, full wordmark), both cropped tight to their ink."""
    image = Image.open(logo).convert("RGBA")
    mark = image.crop((0, 0, round(image.width * MARK_RIGHT), round(image.height * MARK_BOTTOM)))
    mark = mark.crop(mark.getchannel("A").getbbox())
    aspect = mark.width / mark.height
    if not MARK_ASPECT[0] <= aspect <= MARK_ASPECT[1]:
        sys.exit(
            f"KETI mark cropped to {mark.width}x{mark.height} (aspect {aspect:.2f}), which is "
            f"outside the expected {MARK_ASPECT}. The logo layout changed; re-measure "
            "MARK_RIGHT/MARK_BOTTOM."
        )
    wordmark = image.crop(image.getchannel("A").getbbox())
    return mark, wordmark


def fit(art: Image.Image, box: int) -> Image.Image:
    """Scales art to fit a square box, preserving aspect ratio."""
    scale = min(box / art.width, box / art.height)
    size = (max(1, round(art.width * scale)), max(1, round(art.height * scale)))
    return art.resize(size, Image.LANCZOS)


def centred(art: Image.Image, canvas: Image.Image) -> Image.Image:
    canvas = canvas.copy()
    canvas.alpha_composite(
        art,
        ((canvas.width - art.width) // 2, (canvas.height - art.height) // 2),
    )
    return canvas


def rounded_tile(size: int, radius_fraction: float = 0.22) -> Image.Image:
    """A white rounded square, which is what a launcher without adaptive icons shows."""
    tile = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(tile)
    draw.rounded_rectangle(
        (0, 0, size - 1, size - 1),
        radius=round(size * radius_fraction),
        fill=BACKGROUND,
    )
    return tile


def circle_tile(size: int) -> Image.Image:
    tile = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(tile).ellipse((0, 0, size - 1, size - 1), fill=BACKGROUND)
    return tile


def write(path: Path, image: Image.Image) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def brand(app_android: Path, mark: Image.Image, wordmark: Image.Image) -> int:
    res = app_android / "app" / "src" / "main" / "res"
    if not res.exists():
        return 0
    written = 0

    for density, multiplier in DENSITIES.items():
        legacy = round(LEGACY_DP * multiplier)
        # 68% of the tile leaves the mark breathing room inside the rounded corners.
        art = fit(mark, round(legacy * 0.68))
        write(res / f"mipmap-{density}" / "ic_launcher.png", centred(art, rounded_tile(legacy)))
        write(res / f"mipmap-{density}" / "ic_launcher_round.png", centred(art, circle_tile(legacy)))
        written += 2

        # Adaptive foreground: transparent layer, mark sized against the safe zone so the
        # launcher's mask cannot clip the letters.
        layer = round(ADAPTIVE_DP * multiplier)
        safe = round(layer * ADAPTIVE_SAFE_FRACTION * 0.86)
        foreground = Image.new("RGBA", (layer, layer), (0, 0, 0, 0))
        write(
            res / f"drawable-{density}" / "ic_launcher_foreground.png",
            centred(fit(mark, safe), foreground),
        )
        written += 1

        splash_width = round(SPLASH_DP * multiplier)
        splash = wordmark.resize(
            (splash_width, max(1, round(wordmark.height * splash_width / wordmark.width))),
            Image.LANCZOS,
        )
        write(res / f"drawable-{density}" / "splash_keti.png", splash)
        written += 1

        # The system splash icon is a 288dp canvas whose outer ring is masked away, so the
        # mark is fitted to the inner 160dp rather than the full canvas.
        canvas = round(SPLASH_ICON_DP * multiplier)
        write(
            res / f"drawable-{density}" / "splash_icon.png",
            centred(
                fit(mark, round(SPLASH_ICON_CONTENT_DP * multiplier)),
                Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0)),
            ),
        )
        written += 1

    write_text(res / "mipmap-anydpi-v26" / "ic_launcher.xml", ADAPTIVE_XML)
    write_text(res / "mipmap-anydpi-v26" / "ic_launcher_round.xml", ADAPTIVE_XML)
    write_text(res / "values" / "ic_launcher_background.xml", BACKGROUND_XML)
    # Both copies: Flutter ships a drawable-v21 variant and the launch theme resolves the
    # most specific one, so leaving the v21 copy on the stock file would show no logo on
    # every device from Lollipop on.
    write_text(res / "drawable" / "launch_background.xml", LAUNCH_XML)
    write_text(res / "drawable-v21" / "launch_background.xml", LAUNCH_XML)
    write_text(res / "values-v31" / "styles.xml", LAUNCH_V31_XML)
    written += 7
    return written


def main() -> None:
    if not LOGO.exists():
        sys.exit(f"missing {LOGO}")
    mark, wordmark = load_parts(LOGO)
    print(f"mark {mark.width}x{mark.height}, wordmark {wordmark.width}x{wordmark.height}")
    for name, android in APPS:
        count = brand(android, mark, wordmark)
        status = f"{count} files" if count else "skipped (no res dir)"
        print(f"{name:24s} {status}")


if __name__ == "__main__":
    main()
